name: Generate Changelog
on:
  workflow_dispatch:  # Enables manual triggering
    inputs:  # Optional: Define user inputs
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
      version:
        description: 'Application version'
        required: false

jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Generate changelog
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"
