name: Generate Changelog
on:
  workflow_dispatch

jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Generate changelog
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: ./.github/workflows/release.cliff.toml
          args: --verbose --current
        env:
          OUTPUT: CHANGELOG.md

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"
