name: Minimal Reusable Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print Input
      run: echo "Message: ${{ inputs.message }}"
