name: Release a qGuard

on:
  push:
    tags:
      - "v*"

env:
  PRIVATE_PYPI_URL: https://google.com

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout qGuard Repository
      uses: actions/checkout@v3

    - name: call-reusable
      uses: ./.github/workflows/set-up-python-reusable.yml
      with:
        message: "Hello, Reusable Workflow!"

    # - name: List Files
    #   run: ls -R .github/workflows

    # - name: Set Up Environment
    #   uses: ./.github/workflows/set-up-python-reusable.yml
    #   with:
    #     python-version: "3.12.6"

    # - name: Build
    #   id: build
    #   run: |
    #     uv add build
    #     uv run python -m build
    # - name: Publish
    #   env:
    #     TWINE_USERNAME: username
    #     TWINE_PASSWORD: password
    #   run: |
    #     uv add twine
    #     twine upload --repository-url $PRIVATE_PYPI_URL dist/*

    # - name: Generate changelog
    #   run: |
    #     conventional-changelog -p conventionalcommits -i CHANGELOG.md -s -r 1
    #     echo "Changelog generated."

    # - name: Create GitHub Release
    #   uses: actions/create-release@v1
    #   with:
    #     tag_name: ${{ github.ref_name }}
    #     release_name: Release ${{ github.ref_name }}
    #     body_path: CHANGELOG.md
    #     draft: false
    #     prerelease: false

    # - name: Attach Python package to release
    #   uses: actions/upload-release-asset@v1
    #   with:
    #     upload_url: ${{ steps.create-release.outputs.upload_url }}
    #     asset_path: dist/*.tar.gz # Adjust to match your built module
    #     asset_name: qguard-${{ github.ref_name }}.tar.gz
    #     asset_content_type: application/gzip
